CREATE OR REPLACE DATABASE QUIZ_GAME;

CREATE OR REPLACE SEQUENCE QUIZ_GAME.PUBLIC.SEQ
    START = 1
    INCREMENT = 1;

CREATE OR REPLACE TABLE QUIZ_GAME.PUBLIC.QUESTIONS (
    ID INT DEFAULT QUIZ_GAME.PUBLIC.SEQ.NEXTVAL,
    TITLE TEXT,
    CHOICES VARIANT,
    ANSWER TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE QUIZ_GAME.PUBLIC.SCORES (
    ID INT DEFAULT QUIZ_GAME.PUBLIC.SEQ.NEXTVAL,
    USER_ID TEXT,
    SCORE INT,
    USAGE FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE STAGE QUESTIONS_RAW
	DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE FILE FORMAT QUIZ_GAME.PUBLIC.FF_JSON
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE
;
